version: '3.8'
services:

  client:
    container_name: quic-client
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    networks:
      quic-net:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
    volumes:
      - ./certs:/app/certs:rw
      - ./qlogs:/app/qlogs:rw

  server:
    container_name: quic-server
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - 8080:8080
    networks:
      quic-net:
        ipv4_address: 172.16.238.20
    volumes:
      - ./certs:/app/certs:rw
      - ./qlogs:/app/qlogs:rw

  tcpdump:
    image: nicolaka/netshoot
    command: tcpdump -i any -w /tmp/quic.pcap
    network_mode: "service:server"
    volumes:
      - ./pcap:/tmp:rw

networks:
  quic-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
