version: '3.8'
services:

  client:
    container_name: quic-client
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NUM_STREAMS=${NUM_STREAMS:-3}  # Default to 3 if not set
      - PYTHONMALLOC=malloc  # Use system malloc
      - PYTHONUNBUFFERED=1   # Disable output buffering
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 1G
    networks:
      quic-net:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
    volumes:
      - ./certs:/app/certs:rw
      - ./qlogs:/app/qlogs:rw

  server:
    container_name: quic-server
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - PYTHONMALLOC=malloc
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 1G
    ports:
      - 8080:8080
    networks:
      quic-net:
        ipv4_address: 172.16.238.20
    volumes:
      - ./certs:/app/certs:rw
      - ./qlogs:/app/qlogs:rw

  tcpdump:
    image: nicolaka/netshoot
    command: tcpdump -i any -w /tmp/Multiple_Streams.pcap 'udp port 8080'
    network_mode: "service:server"
    volumes:
      - ./pcap:/tmp:rw

networks:
  quic-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
