version: '3'

# Shared volumes for dependency caching
volumes:
  pip-cache:
    driver: local

services:

  client:
    container_name: quic-client-trader1
    build:
      context: .
      dockerfile: ./client/client.Dockerfile
      cache_from:
        - quic-client-trader1
    networks:
      quic-net:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
    volumes:
      - ./certs:/app/certs
      - pip-cache:/root/.cache/pip
    environment:
      - USER_ID=TRADER1
    ports:
      - "8081:6060"

  client2:
    container_name: quic-client-trader2
    build:
      context: .
      dockerfile: ./client/client.Dockerfile
      cache_from:
        - quic-client-trader2
    networks:
      quic-net:
        ipv4_address: 172.16.238.14
    depends_on:
      - server
    volumes:
      - ./certs:/app/certs
      - pip-cache:/root/.cache/pip
    environment:
      - USER_ID=TRADER2
    ports:
      - "8082:6060"

  matching_engine:
    container_name: quic-engine
    build:
      context: .
      dockerfile: ./matching_engine/engine.Dockerfile
      cache_from:
        - quic-engine
    networks:
      quic-net:
        ipv4_address: 172.16.238.12
    depends_on:
      - server
    volumes:
      - ./certs:/app/certs
      - pip-cache:/root/.cache/pip
    environment:
      - USER_ID=MATCHING_ENGINE

  server:
    container_name: quic-server
    build:
      context: .
      dockerfile: ./server/server.Dockerfile
      cache_from:
        - quic-server
    ports:
      - 8080:8080
    networks:
      quic-net:
        ipv4_address: 172.16.238.11
    volumes:
      - ./certs:/app/certs
      - pip-cache:/root/.cache/pip

  web:
    container_name: quic-web-trader1
    build:
      context: .
      dockerfile: ./web_client/web.Dockerfile
      cache_from:
        - quic-web-trader1
    networks:
      quic-net:
        ipv4_address: 172.16.238.13
    depends_on:
      - client
    environment:
      - CLIENT_HOST=quic-client-trader1
      - CLIENT_PORT=6060
      - USER_ID=TRADER1
    volumes:
      - pip-cache:/root/.cache/pip
    ports:
      - "6060:6060"

  web2:
    container_name: quic-web-trader2
    build:
      context: .
      dockerfile: ./web_client/web.Dockerfile
      cache_from:
        - quic-web-trader2
    networks:
      quic-net:
        ipv4_address: 172.16.238.15
    depends_on:
      - client2
    environment:
      - CLIENT_HOST=quic-client-trader2
      - CLIENT_PORT=6060
      - USER_ID=TRADER2
    volumes:
      - pip-cache:/root/.cache/pip
    ports:
      - "6061:6060"

  tcpdump:
    image: nicolaka/netshoot
    command: tcpdump -i any -w /tmp/capture/Order_Matching_Engine.pcap 'udp port 8080'
    network_mode: "host"
    volumes:
      - ../capture:/tmp/capture
    depends_on:
      - client
      - client2
      - server
      - matching_engine

networks:
  quic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
